
name: Deploy Bicep IaC

on:
  workflow_dispatch


jobs:
  whatif:
    name: What If
    runs-on:
      ubuntu-latest
    concurrency: mgmt-tfstate
    environment: alz-mgmt-plan
    permissions:
      id-token: write
      contents: read
    if: ${{ !inputs.skip_what_if }}
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Checkout Bicep Module
        uses: actions/checkout@v4
  
      - name: Get Bicep Variables
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-variables@main
        with:
          parameters_file_name: ${{ env.PARAMETERS_FILE_NAME }}
  
      - name: Get On Demand Folder infra-as-code
        uses: JamesTestOrgGH/alz-mgmt-templates/.github/actions/bicep-on-demand-folder@main
        with:
          repository: "https://github.com/Azure/ALZ-Bicep"
          releaseArtifactName: "accelerator.zip"
          releaseVersion: "${{ env.RELEASE_VERSION }}"
          sourcePath: "infra-as-code"
          targetPath: "infra-as-code"  
