---
name: Validate and WhatIf - Connectivity
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/validate_and_whatif_connectivity.yaml
      - .github/workflows/deploy_connectivity.yaml
      - 'platform/subscriptions/connectivity/**'
  workflow_call:
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: JamesTestOrgGH/alz-mgmt-templates/.github/workflows/validate-whatif-connectivity.yaml@main
    name: 'Validate and Whatif'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
